[tools]
kotlin = "latest"
maven = "latest"
vim = "latest"
dotnet = "latest"
"npm:localtunnel" = "latest"
bun = "latest"
"npm:yarn" = "latest"
"npm:solc" = "latest"
"npm:react-native-cli" = "latest"
"npm:gulp" = "latest"
"npm:ndb" = "latest"
"npm:cordova" = "latest"
"npm:gulp-cli" = "latest"
"npm:flow-bin" = "latest"
"npm:bower" = "latest"
"npm:yo" = "latest"
"npm:generator-webapp" = "latest"
"cargo:cargo-binstall" = "latest"
pnpm = "latest"
scala = "latest"
"npm:grunt-cli" = "latest"
"npm:nativescript" = "latest"
go = "latest"
"npm:tiktok-scraper" = "latest"
deno = "latest"
zig = "latest"
"cargo:syncat" = "latest"
"cargo:paper-terminal" = "latest"
"cargo:ubi" = "0.1.2"
gradle = "latest"
pipx = "latest"
"npm:nodemon" = "latest"
ruby = "latest"
python = "latest"
pixi = "latest"
lua = "latest"
java = "latest"
node = "latest"


[settings]
experimental = true
